version: '2'

services:
  mongosh:
    image: mongo:5
    networks:
      - apt-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5
    networks:
      - apt-network

networks:
  apt-network:
    driver: bridge