on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest-xlarge
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: false

    name: Build with Java ${{ matrix.java }} on macOS
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
    - name: Build with Maven
      run: >
        mvn clean verify
        -Pdocker,jacoco
        org.pitest:pitest-maven:mutationCoverage      